<a href="https://colab.research.google.com/github/KadamShivanjalii/OIBSIP_DataScience_Task1/blob/main/ProblemStatementNo_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
df=sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [7]:
df.isnull().sum().sum()

np.int64(869)

In [8]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [9]:
df.select_dtypes(include=['object','category']).columns

Index(['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive'], dtype='object')

In [10]:
df[['sex','embarked','who']].describe()

         sex embarked  who
count    891      889  891
unique     2        3    3
top     male        S  man
freq     577      644  537

In [11]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [12]:
df.shape

(891, 15)

In [13]:
df['pclass']=df['pclass'].astype('category')

In [15]:
df['age']=df['age'].astype('category')

In [16]:
df.dtypes

survived          int64
pclass         category
sex              object
age            category
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [17]:
df['parch']=df['parch'].astype('float64')

In [18]:
df[['survived','sibsp']]=df[['survived','sibsp']].astype('category')

In [35]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
numcol=df.select_dtypes(include=np.number).columns
numcol

df[numcol]=sc.fit_transform(df[numcol])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0.0,0.014151,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0.0,0.139136,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0.0,0.015469,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0.0,0.103644,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0.0,0.015713,S,Third,man,True,NaN,Southampton,no,True